import { z } from 'zod';
import StatusBadge from '../../components/feedback/StatusBadge';
import { formatCurrency, formatDate } from '../../lib/formatters';

const money = z.coerce.number().positive('Nominal harus lebih dari 0');
const optionalMoney = z.coerce.number().min(0, 'Nominal tidak boleh negatif').optional().or(z.literal(''));
const requiredText = z.string().min(2, 'Minimal 2 karakter');

export const categoryOptions = [
  { value: 'income', label: 'Pemasukan' },
  { value: 'expense', label: 'Pengeluaran' },
  { value: 'both', label: 'Keduanya' },
];

export const needTypeOptions = [
  { value: 'need', label: 'Kebutuhan' },
  { value: 'want', label: 'Keinginan' },
  { value: 'saving', label: 'Tabungan' },
  { value: 'debt', label: 'Utang/Cicilan' },
];

export const accountTypeOptions = [
  { value: 'cash', label: 'Tunai' },
  { value: 'bank', label: 'Bank' },
  { value: 'digital_bank', label: 'Bank digital' },
  { value: 'e_wallet', label: 'E-wallet' },
  { value: 'other', label: 'Lainnya' },
];

export const accountPurposeOptions = [
  { value: 'daily_spending', label: 'Operasional harian' },
  { value: 'salary', label: 'Rekening gaji' },
  { value: 'savings', label: 'Tabungan' },
  { value: 'couple_savings', label: 'Tabungan berdua' },
  { value: 'emergency_fund', label: 'Dana darurat' },
  { value: 'bills', label: 'Tagihan' },
  { value: 'wishlist', label: 'Wishlist/keinginan' },
  { value: 'investment', label: 'Investasi' },
  { value: 'other', label: 'Lainnya' },
];

export const configs = {
  users: {
    title: 'Manajemen User',
    singular: 'user',
    description: 'Kelola user yang dapat masuk ke aplikasi, termasuk role, status akun, dan password login.',
    endpoint: '/users',
    createLabel: 'Tambah user',
    emptyTitle: 'Belum ada user',
    emptyDescription: 'Tambahkan user pertama untuk memberikan akses login email dan password.',
    schema: z.object({
      name: requiredText,
      email: z.string().email('Format email tidak valid'),
      password: z.string().min(8, 'Password minimal 8 karakter').optional().or(z.literal('')),
      role: z.enum(['admin', 'user']),
      status: z.enum(['active', 'inactive']),
    }),
    defaultValues: { name: '', email: '', password: '', role: 'user', status: 'active' },
    toPayload: (values, existing) => {
      const payload = { ...values };
      if (existing && !payload.password) {
        delete payload.password;
      }

      return payload;
    },
    toForm: (row) => ({
      name: row.name || '',
      email: row.email || '',
      password: '',
      role: row.role || 'user',
      status: row.status || 'active',
    }),
    fields: [
      { name: 'name', label: 'Nama user' },
      { name: 'email', label: 'Email', type: 'email' },
      { name: 'password', label: 'Password', type: 'password' },
      { name: 'role', label: 'Role', type: 'select', options: [{ value: 'admin', label: 'Admin' }, { value: 'user', label: 'User' }] },
      { name: 'status', label: 'Status akun', type: 'select', options: [{ value: 'active', label: 'Aktif' }, { value: 'inactive', label: 'Nonaktif' }] },
    ],
    columns: [
      { key: 'name', label: 'Nama' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role', render: (row) => <StatusBadge value={row.role === 'admin' ? 'bank' : 'cash'}>{row.role === 'admin' ? 'Admin' : 'User'}</StatusBadge> },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status === 'active' ? 'active' : 'waiting'}>{row.status === 'active' ? 'Aktif' : 'Nonaktif'}</StatusBadge> },
      { key: 'last_login_at', label: 'Login terakhir', render: (row) => formatDate(row.last_login_at) },
      { key: 'created_at', label: 'Dibuat', render: (row) => formatDate(row.created_at) },
    ],
  },
  accounts: {
    title: 'Manajemen Rekening',
    singular: 'rekening',
    description: 'Pisahkan rekening sesuai fungsi uangnya: harian, gaji, tabungan, dana darurat, tagihan, dan wishlist agar saldo tidak tercampur.',
    endpoint: '/accounts',
    createLabel: 'Tambah rekening',
    emptyTitle: 'Belum ada rekening',
    emptyDescription: 'Buat rekening utama dulu, lalu pisahkan pos tabungan atau dana darurat agar uang aman tidak ikut terpakai.',
    schema: z.object({
      name: requiredText,
      type: z.enum(['cash', 'bank', 'digital_bank', 'e_wallet', 'other']),
      purpose: z.enum(['daily_spending', 'salary', 'savings', 'couple_savings', 'emergency_fund', 'bills', 'wishlist', 'investment', 'other']),
      institution_name: z.string().optional(),
      current_balance: z.coerce.number().min(0, 'Saldo saat ini tidak boleh negatif').optional().or(z.literal('')),
      is_active: z.enum(['1', '0']),
      notes: z.string().optional(),
    }),
    defaultValues: {
      name: '',
      type: 'bank',
      purpose: 'daily_spending',
      institution_name: '',
      current_balance: 0,
      is_active: '1',
      notes: '',
    },
    toPayload: (values, existing) => ({
      ...values,
      institution_name: values.institution_name || null,
      account_identifier: null,
      opening_balance: existing?.opening_balance ?? 0,
      current_balance: values.current_balance || 0,
      is_default: existing?.is_default ?? false,
      is_active: values.is_active === '1',
    }),
    toForm: (row) => ({
      name: row.name || '',
      type: row.type || 'bank',
      purpose: row.purpose || 'daily_spending',
      institution_name: row.institution_name || '',
      current_balance: row.current_balance ?? 0,
      is_active: row.is_active ? '1' : '0',
      notes: row.notes || '',
    }),
    fields: [
      { name: 'name', label: 'Nama rekening' },
      { name: 'type', label: 'Tipe rekening', type: 'select', options: accountTypeOptions },
      { name: 'purpose', label: 'Klasifikasi uang', type: 'select', options: accountPurposeOptions },
      { name: 'institution_name', label: 'Nama bank/e-wallet' },
      { name: 'current_balance', label: 'Saldo saat ini', type: 'number', valueAsNumber: true },
      { name: 'is_active', label: 'Status aktif', type: 'select', options: [{ value: '1', label: 'Aktif' }, { value: '0', label: 'Nonaktif' }] },
      { name: 'notes', label: 'Catatan penggunaan', type: 'textarea', full: true },
    ],
    columns: [
      { key: 'name', label: 'Rekening' },
      { key: 'type', label: 'Tipe', render: (row) => <StatusBadge value={row.type}>{accountTypeOptions.find((item) => item.value === row.type)?.label || row.type}</StatusBadge> },
      { key: 'purpose', label: 'Klasifikasi', render: (row) => <StatusBadge value={row.purpose}>{accountPurposeOptions.find((item) => item.value === row.purpose)?.label || row.purpose}</StatusBadge> },
      { key: 'institution_name', label: 'Institusi', render: (row) => row.institution_name || '-' },
      { key: 'current_balance', label: 'Saldo', render: (row) => formatCurrency(row.current_balance) },
      { key: 'is_default', label: 'Utama', render: (row) => row.is_default ? 'Ya' : 'Tidak' },
      { key: 'is_active', label: 'Status', render: (row) => <StatusBadge value={row.is_active ? 'active' : 'waiting'}>{row.is_active ? 'Aktif' : 'Nonaktif'}</StatusBadge> },
    ],
  },
  categories: {
    title: 'Kategori',
    singular: 'kategori',
    description: 'Buat kategori yang sesuai dengan hidup sehari-hari, bukan kategori yang terlalu akuntansi.',
    endpoint: '/categories',
    createLabel: 'Tambah kategori',
    emptyTitle: 'Belum ada kategori custom',
    emptyDescription: 'Kategori bawaan sudah tersedia. Tambahkan kategori custom kalau ada kebutuhan khusus.',
    schema: z.object({
      name: requiredText,
      transaction_type: z.enum(['income', 'expense', 'both']),
      need_type: z.enum(['need', 'want', 'saving', 'debt']).optional().or(z.literal('')),
      icon: z.string().optional(),
      color: z.string().optional(),
    }),
    defaultValues: { name: '', transaction_type: 'expense', need_type: '', icon: '', color: '#08a0ff' },
    fields: [
      { name: 'name', label: 'Nama kategori' },
      { name: 'transaction_type', label: 'Tipe', type: 'select', options: categoryOptions },
      { name: 'need_type', label: 'Jenis', type: 'select', options: needTypeOptions },
      { name: 'icon', label: 'Icon opsional' },
      { name: 'color', label: 'Warna', type: 'color' },
    ],
    columns: [
      { key: 'name', label: 'Nama' },
      { key: 'transaction_type', label: 'Tipe', render: (row) => <StatusBadge value={row.transaction_type} /> },
      { key: 'need_type', label: 'Jenis', render: (row) => <StatusBadge value={row.need_type}>{row.need_type || '-'}</StatusBadge> },
      { key: 'is_default', label: 'Default', render: (row) => row.is_default ? 'Ya' : 'Tidak' },
    ],
  },
  transactions: {
    title: 'Transaksi',
    singular: 'transaksi',
    description: 'Catat pemasukan dan pengeluaran dengan cepat agar simulasi sampai gajian tetap akurat.',
    endpoint: '/transactions',
    createLabel: 'Tambah transaksi',
    emptyTitle: 'Belum ada transaksi',
    emptyDescription: 'Catat transaksi pertama untuk mulai membaca pola keuangan.',
    schema: z.object({
      transaction_type: z.enum(['income', 'expense']),
      account_id: z.coerce.number().min(1, 'Rekening wajib dipilih'),
      amount: money,
      transaction_date: z.string().min(1, 'Tanggal wajib diisi'),
      category_id: z.coerce.number().optional().or(z.literal('')),
      need_type: z.enum(['need', 'want', 'saving', 'debt']).optional().or(z.literal('')),
      description: z.string().optional(),
      notes: z.string().optional(),
    }),
    defaultValues: { transaction_type: 'expense', account_id: '', amount: '', transaction_date: new Date().toISOString().slice(0, 10), category_id: '', need_type: 'need', description: '', notes: '' },
    fields: [
      { name: 'transaction_type', label: 'Tipe', type: 'select', options: [{ value: 'income', label: 'Pemasukan' }, { value: 'expense', label: 'Pengeluaran' }] },
      { name: 'account_id', label: 'Rekening', type: 'select', optionsKey: 'accounts' },
      { name: 'amount', label: 'Nominal', type: 'number', valueAsNumber: true },
      { name: 'transaction_date', label: 'Tanggal', type: 'date' },
      { name: 'category_id', label: 'Kategori', type: 'select', optionsKey: 'categories' },
      { name: 'need_type', label: 'Kebutuhan/Keinginan', type: 'select', options: needTypeOptions },
      { name: 'description', label: 'Deskripsi', full: true },
      { name: 'notes', label: 'Catatan', type: 'textarea', full: true },
    ],
    columns: [
      { key: 'transaction_date', label: 'Tanggal', render: (row) => formatDate(row.transaction_date) },
      { key: 'description', label: 'Deskripsi' },
      { key: 'transaction_type', label: 'Tipe', render: (row) => <StatusBadge value={row.transaction_type} /> },
      { key: 'account', label: 'Rekening', render: (row) => row.account?.name || '-' },
      { key: 'amount', label: 'Nominal', render: (row) => formatCurrency(row.amount) },
      { key: 'category', label: 'Kategori', render: (row) => row.category?.name || '-' },
    ],
  },
  budgets: {
    title: 'Budget Bulanan',
    singular: 'budget',
    description: 'Tetapkan batas per kategori agar pengeluaran tidak terasa tiba-tiba bocor.',
    endpoint: '/budgets',
    createLabel: 'Tambah budget',
    emptyTitle: 'Belum ada budget',
    emptyDescription: 'Buat budget bulan ini untuk mulai melihat status aman, waspada, atau jebol.',
    schema: z.object({
      month: z.string().min(1),
      planned_income: optionalMoney,
      planned_expense: optionalMoney,
      daily_safe_amount: optionalMoney,
      category_id: z.coerce.number().min(1, 'Kategori wajib dipilih'),
      allocated_amount: money,
    }),
    defaultValues: { month: new Date().toISOString().slice(0, 10), planned_income: '', planned_expense: '', daily_safe_amount: '', category_id: '', allocated_amount: '' },
    toPayload: (values) => ({
      month: values.month,
      planned_income: values.planned_income || 0,
      planned_expense: values.planned_expense || 0,
      daily_safe_amount: values.daily_safe_amount || null,
      status: 'active',
      categories: [{ category_id: values.category_id, allocated_amount: values.allocated_amount }],
    }),
    fields: [
      { name: 'month', label: 'Bulan', type: 'date' },
      { name: 'planned_income', label: 'Rencana pemasukan', type: 'number', valueAsNumber: true },
      { name: 'planned_expense', label: 'Rencana pengeluaran', type: 'number', valueAsNumber: true },
      { name: 'daily_safe_amount', label: 'Target aman harian', type: 'number', valueAsNumber: true },
      { name: 'category_id', label: 'Kategori budget', type: 'select', optionsKey: 'expenseCategories' },
      { name: 'allocated_amount', label: 'Budget kategori', type: 'number', valueAsNumber: true },
    ],
    columns: [
      { key: 'month', label: 'Bulan', render: (row) => formatDate(row.month) },
      { key: 'planned_income', label: 'Pemasukan', render: (row) => formatCurrency(row.planned_income) },
      { key: 'planned_expense', label: 'Pengeluaran', render: (row) => formatCurrency(row.planned_expense) },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> },
    ],
  },
  savings: {
    title: 'Target Tabungan',
    singular: 'target tabungan',
    description: 'Target kecil yang konsisten jauh lebih berguna daripada rencana besar yang terasa mustahil.',
    endpoint: '/saving-goals',
    createLabel: 'Tambah target',
    emptyTitle: 'Belum ada target tabungan',
    emptyDescription: 'Mulai dari target realistis seperti service motor, pulang kampung, atau biaya kesehatan.',
    schema: z.object({
      name: requiredText,
      target_amount: money,
      current_amount: z.coerce.number().min(0).optional().or(z.literal('')),
      target_date: z.string().optional(),
      priority: z.coerce.number().min(1).max(5),
    }),
    defaultValues: { name: '', target_amount: '', current_amount: 0, target_date: '', priority: 3, type: 'saving' },
    toPayload: (values) => ({ ...values, type: 'saving', current_amount: values.current_amount || 0, status: 'active' }),
    fields: [
      { name: 'name', label: 'Nama target' },
      { name: 'target_amount', label: 'Target nominal', type: 'number', valueAsNumber: true },
      { name: 'current_amount', label: 'Sudah terkumpul', type: 'number', valueAsNumber: true },
      { name: 'target_date', label: 'Target tanggal', type: 'date' },
      { name: 'priority', label: 'Prioritas 1-5', type: 'number', valueAsNumber: true },
    ],
    columns: [
      { key: 'name', label: 'Target' },
      { key: 'current_amount', label: 'Terkumpul', render: (row) => formatCurrency(row.current_amount) },
      { key: 'target_amount', label: 'Target', render: (row) => formatCurrency(row.target_amount) },
      { key: 'progress_percent', label: 'Progress', render: (row) => `${row.progress_percent}%` },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> },
    ],
  },
  bills: {
    title: 'Tagihan Rutin',
    singular: 'tagihan',
    description: 'Amankan tagihan sebelum jatuh tempo agar tidak terkena denda kecil yang menyakitkan.',
    endpoint: '/recurring-bills',
    createLabel: 'Tambah tagihan',
    emptyTitle: 'Belum ada tagihan',
    emptyDescription: 'Tambahkan kos, internet, cicilan, atau paket data rutin.',
    schema: z.object({
      name: requiredText,
      amount_estimate: money,
      due_day: z.coerce.number().min(1).max(31).optional().or(z.literal('')),
      next_due_date: z.string().optional(),
      frequency: z.enum(['weekly', 'monthly', 'yearly', 'once']),
    }),
    defaultValues: { name: '', amount_estimate: '', due_day: '', next_due_date: '', frequency: 'monthly' },
    fields: [
      { name: 'name', label: 'Nama tagihan' },
      { name: 'amount_estimate', label: 'Nominal', type: 'number', valueAsNumber: true },
      { name: 'due_day', label: 'Tanggal jatuh tempo', type: 'number', valueAsNumber: true },
      { name: 'next_due_date', label: 'Jatuh tempo berikutnya', type: 'date' },
      { name: 'frequency', label: 'Frekuensi', type: 'select', options: [{ value: 'weekly', label: 'Mingguan' }, { value: 'monthly', label: 'Bulanan' }, { value: 'yearly', label: 'Tahunan' }, { value: 'once', label: 'Sekali' }] },
    ],
    columns: [
      { key: 'name', label: 'Tagihan' },
      { key: 'amount_estimate', label: 'Nominal', render: (row) => formatCurrency(row.amount_estimate) },
      { key: 'next_due_date', label: 'Jatuh tempo', render: (row) => formatDate(row.next_due_date) },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> },
    ],
  },
  wishlist: {
    title: 'Wishlist Tertahan',
    singular: 'wishlist',
    description: 'Bantu diri sendiri menunda pembelian impulsif tanpa merasa dilarang.',
    endpoint: '/wishlist',
    createLabel: 'Tambah wishlist',
    emptyTitle: 'Belum ada wishlist',
    emptyDescription: 'Catat barang yang ingin dibeli, lalu beri waktu tunggu sebelum memutuskan.',
    schema: z.object({
      name: requiredText,
      estimated_amount: money,
      need_type: z.enum(['need', 'want']),
      waiting_days: z.coerce.number().min(0).max(90),
      status: z.enum(['waiting', 'approved', 'converted_to_goal', 'bought', 'cancelled']),
      notes: z.string().optional(),
    }),
    defaultValues: { name: '', estimated_amount: '', need_type: 'want', waiting_days: 7, status: 'waiting', notes: '' },
    fields: [
      { name: 'name', label: 'Nama item' },
      { name: 'estimated_amount', label: 'Estimasi harga', type: 'number', valueAsNumber: true },
      { name: 'need_type', label: 'Jenis', type: 'select', options: [{ value: 'need', label: 'Kebutuhan' }, { value: 'want', label: 'Keinginan' }] },
      { name: 'waiting_days', label: 'Masa tunggu (hari)', type: 'number', valueAsNumber: true },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'waiting', label: 'Menunggu' }, { value: 'approved', label: 'Direncanakan' }, { value: 'bought', label: 'Dibeli' }, { value: 'cancelled', label: 'Dibatalkan' }, { value: 'converted_to_goal', label: 'Jadi target' }] },
      { name: 'notes', label: 'Catatan', type: 'textarea', full: true },
    ],
    columns: [
      { key: 'name', label: 'Item' },
      { key: 'estimated_amount', label: 'Harga', render: (row) => formatCurrency(row.estimated_amount) },
      { key: 'need_type', label: 'Jenis', render: (row) => <StatusBadge value={row.need_type} /> },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> },
    ],
  },
  recurringTransactions: {
    title: 'Transaksi Rutin',
    singular: 'transaksi rutin',
    description: 'Simpan template gaji, kirim uang keluarga, paket data, atau pengeluaran yang berulang.',
    endpoint: '/recurring-transactions',
    createLabel: 'Tambah transaksi rutin',
    emptyTitle: 'Belum ada transaksi rutin',
    emptyDescription: 'Tambahkan transaksi rutin agar perencanaan sampai gajian lebih akurat.',
    schema: z.object({
      name: requiredText,
      transaction_type: z.enum(['income', 'expense']),
      amount: money,
      category_id: z.coerce.number().optional().or(z.literal('')),
      frequency: z.enum(['daily', 'weekly', 'monthly', 'yearly']),
      day_of_month: z.coerce.number().min(1).max(31).optional().or(z.literal('')),
      next_run_date: z.string().optional(),
      notes: z.string().optional(),
    }),
    defaultValues: { name: '', transaction_type: 'expense', amount: '', category_id: '', frequency: 'monthly', day_of_month: '', next_run_date: '', notes: '' },
    toPayload: (values) => ({ ...values, category_id: values.category_id || null, day_of_month: values.day_of_month || null, status: 'active' }),
    fields: [
      { name: 'name', label: 'Nama template' },
      { name: 'transaction_type', label: 'Tipe', type: 'select', options: [{ value: 'income', label: 'Pemasukan' }, { value: 'expense', label: 'Pengeluaran' }] },
      { name: 'amount', label: 'Nominal', type: 'number', valueAsNumber: true },
      { name: 'category_id', label: 'Kategori', type: 'select', optionsKey: 'categories' },
      { name: 'frequency', label: 'Frekuensi', type: 'select', options: [{ value: 'daily', label: 'Harian' }, { value: 'weekly', label: 'Mingguan' }, { value: 'monthly', label: 'Bulanan' }, { value: 'yearly', label: 'Tahunan' }] },
      { name: 'day_of_month', label: 'Tanggal tiap bulan', type: 'number', valueAsNumber: true },
      { name: 'next_run_date', label: 'Jadwal berikutnya', type: 'date' },
      { name: 'notes', label: 'Catatan', type: 'textarea', full: true },
    ],
    columns: [
      { key: 'name', label: 'Nama' },
      { key: 'transaction_type', label: 'Tipe', render: (row) => <StatusBadge value={row.transaction_type} /> },
      { key: 'amount', label: 'Nominal', render: (row) => formatCurrency(row.amount) },
      { key: 'frequency', label: 'Frekuensi' },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> },
    ],
  },
  periods: {
    title: 'Manajemen Periode',
    singular: 'periode',
    description: 'Atur periode finansial agar budget, payday, dan laporan bulanan punya batas waktu yang jelas.',
    endpoint: '/periods',
    createLabel: 'Tambah periode',
    emptyTitle: 'Belum ada periode',
    emptyDescription: 'Buat periode gajian atau bulan berjalan untuk merapikan perencanaan uang.',
    schema: z.object({
      name: requiredText,
      start_date: z.string().min(1, 'Tanggal mulai wajib diisi'),
      end_date: z.string().min(1, 'Tanggal akhir wajib diisi'),
      payday_date: z.string().optional(),
      status: z.enum(['planned', 'active', 'closed']),
      notes: z.string().optional(),
    }),
    defaultValues: {
      name: '',
      start_date: new Date().toISOString().slice(0, 10),
      end_date: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0).toISOString().slice(0, 10),
      payday_date: '',
      status: 'planned',
      notes: '',
    },
    fields: [
      { name: 'name', label: 'Nama periode' },
      { name: 'status', label: 'Status', type: 'select', options: [{ value: 'planned', label: 'Direncanakan' }, { value: 'active', label: 'Aktif' }, { value: 'closed', label: 'Ditutup' }] },
      { name: 'start_date', label: 'Tanggal mulai', type: 'date' },
      { name: 'end_date', label: 'Tanggal akhir', type: 'date' },
      { name: 'payday_date', label: 'Tanggal gajian', type: 'date' },
      { name: 'notes', label: 'Catatan', type: 'textarea', full: true },
    ],
    columns: [
      { key: 'name', label: 'Periode' },
      { key: 'start_date', label: 'Mulai', render: (row) => formatDate(row.start_date) },
      { key: 'end_date', label: 'Selesai', render: (row) => formatDate(row.end_date) },
      { key: 'status', label: 'Status', render: (row) => <StatusBadge value={row.status} /> },
    ],
  },
};
